FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY exfil-listener/ ./exfil-listener/

WORKDIR /app/exfil-listener
EXPOSE 8888
CMD ["python", "app.py"]
