services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.2
    hostname: wazuh-certs-generator
    volumes:
      - ./certs/config.yml:/config/certs.yml
      - ./certs/wazuh-indexer-certs:/certificates/
    entrypoint: sh -c "/entrypoint.sh"
